accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

wine_shop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from wines import views as wine_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wines/',include('wines.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^$', wine_views.wine_list,name="home"),
    
]

urlpatterns += staticfiles_urlpatterns()

wines/urls.py
from django.conf.urls import url
from . import views


#namespaceing
app_name = 'wines'

urlpatterns = [
    url(r'^$', views.wine_list,name="list"),
    url(r'^wine_search/$',views.wine_search,name="search"),
    url(r'^wine_sort/$',views.wine_sort,name="sort"),
    # url(r'^wine_search_grape/$',views.wine_search_grape,name="search_grape"),
    url(r'^(?P<slug>[\w-]+)/$',views.wine_detail,name="detail"),


]

accounts/models.py
from django.db import models

# Create your models here.

wines/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

# this is the models file where we define the model for the user and admin
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Test(models.Model):
    country = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    designation = models.CharField(max_length=255, blank=True, null=True)
    points = models.IntegerField(blank=True, null=True)
    province = models.CharField(max_length=255, blank=True, null=True)
    region_1 = models.CharField(max_length=255, blank=True, null=True)
    region_2 = models.CharField(max_length=255, blank=True, null=True)
    variety = models.CharField(max_length=255, blank=True, null=True)
    winery = models.CharField(max_length=255, blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'test'

    def __str__(self):
        return self.winery

    def snippet(self):
        return self.description[:50]+'...'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('wines:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            return redirect('wines:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('wines:list')

wines/views.py
from django.shortcuts import render
from .models import Test
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q


@login_required(login_url="/accounts/login")
# Create your views here.
def wine_list(request):
	wine_list = Test.objects.all()
	paginator = Paginator(wine_list,20)
	page = request.GET.get('page')
	wines = paginator.get_page(page)
	return render(request,'wines/wine_list.html',{'wines':wines})

def wine_search(request):
	query1 = request.GET.get('search-place-box')
	query2 = request.GET.get('search-grape-box')
	if query1 == "":
		wine_list = Test.objects.filter(Q(variety__icontains=query2))
	else:
		wine_list = Test.objects.filter((Q(country=query1)  | Q(province=query1) | Q(region_1=query1) | Q(region_2=query1)) & Q(variety__icontains=query2))
	paginator = Paginator(wine_list,20)
	page = request.GET.get('page')
	wines = paginator.get_page(page)
	return render(request,'wines/wine_list.html',{'wines':wines})

# def wine_search_grape(request):
# 	query = request.GET.get('search-grape-box')
# 	wines = Test.objects.filter(Q(variety__icontains=query))
# 	return render(request,'wines/wine_list.html',{'wines':wines})

def wine_sort(request):
	# return HttpResponse("sagar")
	wine_list = Test.objects.all().order_by('-price')
	paginator = Paginator(wine_list,20)
	page = request.GET.get('page')
	wines = paginator.get_page(page)
	return render(request,'wines/wine_list.html',{'wines':wines})

def wine_detail(request,slug):
	 # return HttpResponse(slug)
	var = Test.objects.get(id=slug)
	return render(request,'wines/wine_detail.html',{'wine':var})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
 
<!DOCTYPE html>
<html>
<head>
	<title>Wines</title>
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
	<body>
		<header class="wrapper">
            <h1><a href="{% url 'home' %}"><img class="logo" src="{% static 'logo.png' %}" alt="Wines" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
		</header>
		<div class="wrapper">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

wines/templates/wines/wine_detail.html
{% extends 'base_layout.html' %}

{% block content %}
	<div class="wine-detail">
		<div class="wine">
			<h2>{{ wine.winery }}</h2>
			<p>{{ wine.description }}</p>
			<p><b style="color:#00dba0">Designation : </b>{{ wine.designation }}</p>
			<p><b style="color:#00dba0">Points: </b>{{ wine.points }}</p>
			<p><b style="color:#00dba0">Country: </b>{{ wine.country }}</p>
			<p><b style="color:#00dba0">Province: </b>{{ wine.province }}</p>
			<p><b style="color:#00dba0">Regions: </b>{{ wine.region_1 }} , {{ wine.region_2 }}</p>
			<p><b style="color:#00dba0">Variety: </b>{{ wine.variety }}</p>
			<p><b style="color:#00dba0">Price: </b>{{ wine.price }}</p>
		</div>
	</div>
{% endblock %}

wines/templates/wines/wine_list.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}

{% block content %}
<form class="search" action="{% url 'wines:search' %}" method="GET" type="get">
	{% csrf_token %}
	<input class="search-box" type="text" placeholder="Enter a Country, Province, Region" name="search-place-box">
	<input class="search-box" type="text" placeholder="Enter a grape type" name="search-grape-box"><br>
	<button class ="submit" type="submit">Filter</button>
</form>
<form class="sort" action="{% url 'wines:sort' %}" method="GET">
	{% csrf_token %}
	<button class="submit" type="submit">Sort</button>
</form>
	<h1>Wines List</h1>
	<div class="wines">
		<table>
			<tr><th>Winery</th>
			<th>Description</th>
			<th>Country</th>
			<th>Province</th>
			<th>Region_1</th>
			<th>Region_2</th>
			<th>Variety</th>
			<th>Price</th>
		</tr>
			{% for wine in wines %}
				<div class="wine">
					<tr>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.winery}}</a></td>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.snippet}}</a></td>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.country}}</a></td>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.province}}</a></td>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.region_1}}</a></td>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.region_2}}</a></td>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.variety}}</a></td>
					<td><a href="{% url 'wines:detail' slug=wine.id %}">{{wine.price}}</a></td>
					</tr>
				</div>
			{% endfor %}
		</table><br>
		<div class="pagination">
    <span class="step-links">
        {% if wines.has_previous %}
            <a href="?page=1">&laquo; first</a>&nbsp;&nbsp;
            <a href="?page={{ wines.previous_page_number }}">previous</a>&nbsp;&nbsp;
        {% endif %}

        <span class="current">
            Page {{ wines.number }} of {{ wines.paginator.num_pages }}.&nbsp;&nbsp;
        </span>

        {% if wines.has_next %}
            <a href="?page={{ wines.next_page_number }}">next</a>&nbsp;&nbsp;
            <a href="?page={{ wines.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
	</div>
{% endblock %}